config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

my_dj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),            # 保留 admin
    path('myapp/', include('myapp.urls')),      # 存取 myapp 的 url
    path('tem_app/', include('tem_app.urls')),  # 存取 tem_app 的 url
    path('url/', include ('url_app.urls', namespace='url')),     # 存取 url_app 的 url
]

myapp/urls.py
from django.urls import path
from . import views             # 同目录下的 views.py

urlpatterns = [
    path('', views.index, name='index'),    # 弯弯的月亮 api
    path('sun/', views.sun, name='sun'),    # 灿烂的太阳 api
    path('star/', views.star, name='star'), # 闪烁的星星 api
]

tem_app/urls.py
from django.urls import path
# from tem_app.views import tem_var                     # 同目录下的 views.py
from tem_app.views import tem_var, pass_dict, pass_obj  # 导入多个 views 时用逗号分隔

urlpatterns = [
    path("var/<name>/", tem_var),
    path("dict/", pass_dict),
    path("obj/", pass_obj),
]

url_app/urls.py
from django.urls import path
from url_app.views import go_reverse, get_url, show_hobby, get_reverse

app_name = 'url'

urlpatterns = [
    path("reverse/",go_reverse, name="reverse"),
    path("hello/", get_url, name="hello"),
    path("show/<fruit>/<sport>", show_hobby, name="show"),
    path("view/", get_reverse, name="view"),
]

url_app/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("弯弯的月亮")   # 满足题目要求 3

def sun(request):
    return HttpResponse("灿烂的太阳")   # 满足题目要求 1

def star(request):
    return HttpResponse("闪烁的星星")   # 满足题目要求 2

tem_app/views.py
from django.shortcuts import render
from .person import Person

# Create your views here.
def tem_var(request, name):
    return render(request, "show_var.html", {"name": name})
    # it will display the text after api endpoint as header
    # e.g. http://127.0.0.1:8000/tem_app/var/12345/
    # will show: "12345" as header

def pass_dict(request):
    sample = {
        "name": "Django",
        "teacher": "Dr. Su"
    }
    return render(request, "show_info.html", {"product": sample})

def pass_obj(request):
    rick = Person("Rick", 80)
    return render(request, "show_info.html", {"person": rick})

url_app/views.py
from django.shortcuts import render, redirect
from django.http import (
    HttpResponse,          # 基本的HTTP响应
    JsonResponse,          # 返回JSON数据
    HttpResponseRedirect,  # HTTP重定向
    HttpResponseNotFound,  # 404错误
    HttpResponseBadRequest,# 400错误
    HttpResponseForbidden,# 403错误
    HttpResponseServerError,# 500错误
)
from django.urls import reverse

# Create your views here.
def go_reverse(request):
    return render(request,"reverse.html")



def get_url(request):
    return render(request,"hello.html")

def show_hobby(request, fruit,sport):
    msg = f"my favorite fruit is {fruit}; my favorite sport is {sport}"
    return HttpResponse(f"<h3>{msg}</h3>")

def get_reverse(request):
    fruit = "Banana"
    sport = "Skydiving"
    #eturn redirect(reverse("url:show",args=(fruit, sport)))
    return redirect(reverse("url:show",kwgs={"fruit":fruit, "sport": sport}))

tem_app/templates/show_info.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>点语法访问复杂对象</title>

</head>

<body>
    <h3> 课程名称： {{ product.name }} </H3>
    <h3> 教师名称： {{ product.teacher }} </h3> 

    <h3> 明星：     {{ person.name }} </h3>
    
</body>
</html>

tem_app/templates/show_var.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>title</title>

</head>

<body>
<h3>{{ name }}</H3> 
</body>
</html>

url_app/templates/hello.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>URL反向解析的跳转</title>

</head>

<body>
Hello World

</body>
</html>

url_app/templates/reverse.html
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>URL 反向解析</title>

</head>

<body>
不传参的反向解析：<a href="{% url 'url:hello' %}">反向解析</a>
<hr><br>
传参的反向解析:<a href="{% url 'url:show' 'apple' 'F1'%}">传参的反向解析</a>
<hr><br>
视图函数的反向解析：<a href="{% url 'url:view' %}">视图函数的反向解析</a>

</body>
</html>